# Generated by Django 3.2.1 on 2021-05-06 09:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_evalution_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='companies',
            field=models.ManyToManyField(null=True, through='customer.Evalution', to='customer.Company'),
        ),
        migrations.AddField(
            model_name='evaluationexpert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_end',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 6, 9, 34, 45, 317618, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_start',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 6, 9, 34, 45, 317618, tzinfo=utc)),
        ),
    ]
