# Generated by Django 3.2.1 on 2021-05-05 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='insurer_end',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 5, 19, 58, 22, 465526, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_start',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 5, 19, 58, 22, 465526, tzinfo=utc)),
        ),
    ]
