# Generated by Django 3.2.1 on 2021-05-07 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='companies',
            field=models.ManyToManyField(through='user.Evalution', to='customer.Company'),
        ),
        migrations.AddField(
            model_name='cuser',
            name='permissions',
            field=models.ManyToManyField(through='user.UserPermission', to='user.Permission'),
        ),
        migrations.AddField(
            model_name='evaluationexpert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uer_evaluation_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evalution',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.company'),
        ),
        migrations.AddField(
            model_name='evalution',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_expeter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cpermission_users', to='user.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_cpermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
