# Generated by Django 3.2.1 on 2021-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210507_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='username',
            field=models.CharField(default='test', max_length=150, unique=True),
        ),
    ]
