# Generated by Django 3.2.1 on 2021-05-06 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210506_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationexpert',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uer_evaluation_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_end',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 6, 10, 22, 52, 758520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_start',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2021, 5, 6, 10, 22, 52, 758520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_insurer', to=settings.AUTH_USER_MODEL),
        ),
    ]
