# Generated by Django 3.2.1 on 2021-05-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210506_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='insurer_start',
            field=models.DateField(null=True),
        ),
    ]
