# Generated by Django 3.2.1 on 2021-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_evalution_user'),
        ('user', '0004_auto_20210506_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='companies',
            field=models.ManyToManyField(through='customer.Evalution', to='customer.Company'),
        ),
    ]
