# Generated by Django 3.2.1 on 2021-05-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivationCode',
        ),
    ]
